# -*- coding: utf-8 -*-
"""Prediksi harga mobil bekas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12e3FwJ0aEJVdbh8pnwWXDgn-LfH9s2bm

# Data Collection
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

car_df = pd.read_csv('cardekho.csv')
car_df.head(10)

car_df.info()

"""# Data Understanding

## Remove null value
"""

car_df.isnull().sum()

car_df = car_df.dropna()

"""## Remove Duplicate Data"""

duplicate_rows = car_df.duplicated()

# print duplicate rows
print(duplicate_rows.sum())

car_df = car_df.drop_duplicates()

car_df.info()

"""## Change data type and column name"""

car_df['max_power'] = car_df['max_power'].astype('float')

car_df[car_df['max_power'] == ' ']

car_df['max_power'] = car_df['max_power'].replace(' ', np.nan)

car_df = car_df.dropna(subset=['max_power'])

car_df[car_df['max_power'] == ' ']

car_df['max_power'] = car_df['max_power'].astype('float')

car_df['seats'] = car_df['seats'].astype(int)

car_df.info()

car_df.rename(columns={'mileage(km/ltr/kg)':'mileage'}, inplace = True)

car_df.describe()

"""## Remove Outlier"""

sns.boxplot(x=car_df['selling_price'])

sns.boxplot(x=car_df['km_driven'])

sns.boxplot(x=car_df['mileage'])

sns.boxplot(x=car_df['engine'])

sns.boxplot(x=car_df['max_power'])

num_features = ['selling_price',	'km_driven',	'mileage',	'engine',	'max_power']
car_df[num_features]

Q1 = car_df[num_features].quantile(0.25)
Q3 = car_df[num_features].quantile(0.75)
IQR=Q3-Q1
car_df=car_df[~((car_df[num_features]<(Q1-1.5*IQR))|(car_df[num_features]>(Q3+1.5*IQR))).any(axis=1)]

car_df.info()

"""## EDA"""

cat_features = ['year', 'name',	'fuel',	'seller_type', 'transmission', 'owner', 'seats']

"""### Univariate Analysis

#### Categorical Features
"""

feature = cat_features[0]
count = car_df[feature].value_counts()
percent = 100*car_df[feature].value_counts(normalize=True)

top_5_count = count.head(5)
top_5_percent = percent.head(5)

df = pd.DataFrame({'jumlah sampel':top_5_count, 'persentase':top_5_percent.round(1)})
print(df)
top_5_count.plot(kind='bar', title=feature);

feature = cat_features[1]
count = car_df[feature].value_counts()
percent = 100*car_df[feature].value_counts(normalize=True)

top_5_count = count.head(5)
top_5_percent = percent.head(5)

df = pd.DataFrame({'jumlah sampel':top_5_count, 'persentase':top_5_percent.round(1)})
print(df)
top_5_count.plot(kind='bar', title=feature);

feature = cat_features[2]
count = car_df[feature].value_counts()
percent = 100*car_df[feature].value_counts(normalize=True)

df = pd.DataFrame({'jumlah sampel':count, 'persentase':percent.round(1)})
print(df)
count.plot(kind='bar', title=feature);

feature = cat_features[3]
count = car_df[feature].value_counts()
percent = 100*car_df[feature].value_counts(normalize=True)

df = pd.DataFrame({'jumlah sampel':count, 'persentase':percent.round(1)})
print(df)
count.plot(kind='bar', title=feature);

feature = cat_features[4]
count = car_df[feature].value_counts()
percent = 100*car_df[feature].value_counts(normalize=True)

df = pd.DataFrame({'jumlah sampel':count, 'persentase':percent.round(1)})
print(df)
count.plot(kind='bar', title=feature);

feature = cat_features[5]
count = car_df[feature].value_counts()
percent = 100*car_df[feature].value_counts(normalize=True)

top_5_count = count.head(5)
top_5_percent = percent.head(5)

df = pd.DataFrame({'jumlah sampel':top_5_count, 'persentase':top_5_percent.round(1)})
print(df)
top_5_count.plot(kind='bar', title=feature);

feature = cat_features[6]
count = car_df[feature].value_counts()
percent = 100*car_df[feature].value_counts(normalize=True)

top_5_count = count.head(5)
top_5_percent = percent.head(5)

df = pd.DataFrame({'jumlah sampel':top_5_count, 'persentase':top_5_percent.round(1)})
print(df)
top_5_count.plot(kind='bar', title=feature);

"""#### Numerical Features"""

car_df.hist(bins=50, figsize=(20,15))
plt.show()

"""### Multivariate Analysis"""

for col in cat_features:
  sns.catplot(x=col, y="selling_price", kind="bar", dodge=False, height = 4, aspect = 3,  data=car_df, palette="Set3")
  plt.title("Rata-rata 'selling_price' Relatif terhadap - {}".format(col))

sns.pairplot(car_df, diag_kind = 'kde')

"""### Correlasion Matrix"""

plt.figure(figsize=(10, 8))
correlation_matrix = car_df[num_features].corr().round(2)

# Untuk menge-print nilai di dalam kotak, gunakan parameter anot=True
sns.heatmap(data=correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5, )
plt.title("Correlation Matrix untuk Fitur Numerik ", size=20)

car_df.head()

"""# Data Preparation"""

from sklearn.preprocessing import TargetEncoder, LabelEncoder

target_encoder = TargetEncoder()
label_encoder = LabelEncoder()

"""## Target Encoding"""

car_df['selling_price_log'] = np.log1p(car_df['selling_price'])
car_df['name']= target_encoder.fit_transform(car_df[['name']], car_df['selling_price_log'])

car_df.head()

"""## Label Encoding"""

car_df['fuel']= label_encoder.fit_transform(car_df['fuel'])

car_df['fuel'].unique()

car_df['seller_type']= label_encoder.fit_transform(car_df['seller_type'])

car_df['seller_type'].unique()

car_df['transmission']= label_encoder.fit_transform(car_df['transmission'])

car_df['transmission'].unique()

car_df['owner']= label_encoder.fit_transform(car_df['owner'])

car_df['owner'].unique()

car_df.head()

car_df.drop(['selling_price_log'], axis = 1, inplace = True)

car_df.head()

"""## Train-Test_Split"""

x = car_df.drop(['selling_price'], axis = 1)
y = car_df['selling_price']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

print(f'Total # of sample in whole dataset: {len(x)}')
print(f'Total # of sample in train dataset: {len(x_train)}')
print(f'Total # of sample in test dataset: {len(x_test)}')

"""## Standarization"""

from sklearn.preprocessing import StandardScaler

numerical_features = ['km_driven',	'mileage',	'engine',	'max_power']
scaler = StandardScaler()
scaler.fit(x_train[numerical_features])
x_train[numerical_features] = scaler.transform(x_train.loc[:, numerical_features])
x_train[numerical_features].head()

"""# Modeling"""

models = pd.DataFrame(index=['train_mse', 'test_mse'],
                      columns=[ 'RandomForest', 'XGBoost', 'GradientBoosting'])

from sklearn.metrics import mean_squared_error

"""## Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100, random_state=123)
rf.fit(x_train, y_train)

models.loc['train_mse','RandomForest'] = mean_squared_error(y_pred = rf.predict(x_train), y_true=y_train)

"""## XGBoost"""

!pip install xgboost

import xgboost as xgb

xgb_r = xgb.XGBRegressor(objective ='reg:squarederror', random_state=123)
xgb_r.fit(x_train, y_train)

models.loc['train_mse','XGBoost'] = mean_squared_error(y_pred=xgb_r.predict(x_train), y_true=y_train)

"""## Gradient Boosting"""

from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(n_estimators=200, learning_rate=0.1, random_state=1)
gbr.fit(x_train, y_train)

models.loc['train_mse','GradientBoosting'] = mean_squared_error(y_pred=gbr.predict(x_train), y_true=y_train)

"""# Evaluation"""

x_test.loc[:, numerical_features] = scaler.transform(x_test[numerical_features])

mse = pd.DataFrame(columns=['train', 'test'], index=['RF','XGBoost','GradientBoosting'])

# Buat dictionary untuk setiap algoritma yang digunakan
model_dict = { 'RF': rf, 'XGBoost':xgb_r, 'GradientBoosting':gbr}

# Hitung Mean Squared Error masing-masing algoritma pada data train dan test
for name, model in model_dict.items():
    mse.loc[name, 'train'] = mean_squared_error(y_true=y_train, y_pred=model.predict(x_train))/1e3
    mse.loc[name, 'test'] = mean_squared_error(y_true=y_test, y_pred=model.predict(x_test))/1e3

# Panggil mse
mse

fig, ax = plt.subplots()
mse.sort_values(by='test', ascending=False).plot(kind='barh', ax=ax, zorder=3)
ax.grid(zorder=0)

prediksi = x_test.iloc[:5].copy()
pred_dict = {'y_true':y_test[:5]}
for name, model in model_dict.items():
    pred_dict['prediksi_'+name] = model.predict(prediksi).round(1)

pd.DataFrame(pred_dict)